# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: dk.ehealth.sundhed.fhir.ig.core
canonical: http://ehealth.sundhed.dk/fhir
name: eHealth Infrastructure
title: eHealth Infrastructure
status: draft
version: latest
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
description: The Danish eHealth Infrastructure Implementation Guide defines a set of FHIR profiles with extensions and bindings needed to create interoperable, quality-focused applications.

publisher:
  name: Systematic | Trifork
  url: http://ehealth.sundhed.dk

dependencies:
  dk.fhir.ig.dk-core: current

# No apparant influence of this global definition? Check eg. ehealth-careplan.instantiatesCanonical 
global:
  Patient: http://ehealth.sundhed.dk/fhir/StructureDefinition/ehealth-patient
  PlanDefinition: http://ehealth.sundhed.dk/fhir/StructureDefinition/ehealth-plandefinition
  Questionnaire: http://ehealth.sundhed.dk/fhir/StructureDefinition/ehealth-questionnaire
  QuestionnaireResponse: http://ehealth.sundhed.dk/fhir/StructureDefinition/ehealth-questionnaireresponse

parameters: # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources

  usage-stats-opt-out: true

pages:
  index.md:
    title: eHealth Infrastructure Implementation Guide
  guidance.md:
    title: General guidance
  profiles.md:
  operations.md:
  searchparams.md:
    title: Search Parameters
  error-messages.md:
  service-event-tables.md:
  event-messages.md:
  downloads.md:
  terminology.md:

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Table of Contents: toc.html
  Home: index.html
  General guidance: guidance.html
  FHIR Artifacts:
    Profiles and extensions: profiles.html
    Search Parameters: searchparams.html
    Operations: operations.html
  Artifacts Summary: artifacts.html
  Terminology: terminology.html
  Events:
    Event message types: event-messages.html
    Service event messages: service-event-tables.html
  Error Messsages: error-messages.html
  Capability Statements:
      Patient service:  CapabilityStatement-patient.html
  #Capability Statements: capability-statements.html
  Downloads: downloads.html
