# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: dk.ehealth.sundhed.fhir.ig.core
canonical: http://ehealth.sundhed.dk/fhir
name: eHealth Infrastructure
title: eHealth Infrastructure
status: draft
version: 0.7.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
description: The Danish eHealth Infrastructure Implementation Guide defines a set of FHIR profiles with extensions and bindings needed to create interoperable, quality-focused applications.

publisher:
  name: Systematic | Trifork
  url: http://ehealth.sundhed.dk

dependencies:
  dk.fhir.ig.dk-core: current
  hl7.fhir.uv.sdc: current

parameters: # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources

  path-pages:
    - input/includes

  usage-stats-opt-out: true
  show-inherited-invariants: false

pages:
  index.md:
    title: eHealth Infrastructure Implementation Guide
  guidance.md:
    title: General guidance
  profiles.md:
  operations.md:
  example-operations.md:
  searchparams.md:
    title: Search Parameters
  error-messages.md:
  service-event-tables.md:
  event-messages.md:
  downloads.md:
  terminology.md:
  changelog.md:

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Table of Contents: toc.html
  Home: index.html
  General guidance: guidance.html
  FHIR Artifacts:
    Profiles and extensions: profiles.html
    Search Parameters: searchparams.html
    Operations: operations.html
    Operation examples: example-operations.html
  Artifacts Summary: artifacts.html
  Terminology: terminology.html
  Events:
    Event message types: event-messages.html
    Service event messages: service-event-tables.html
  Error Messsages: error-messages.html
  Capability Statements:
    CarePlan service: CapabilityStatement-careplan.html
    Device service: CapabilityStatement-device.html
    DocumentQuery service: CapabilityStatement-document-query.html
    DocumentTransformation service: CapabilityStatement-document-transformation.html
    Library service: CapabilityStatement-library.html
    Measurement service: CapabilityStatement-measurement.html
    Organization service: CapabilityStatement-organization.html
    Patient service:  CapabilityStatement-patient.html
    Plan service: CapabilityStatement-plan.html
    Questionnaire service: CapabilityStatement-questionnaire.html
    Reporting service: CapabilityStatement-reporting.html
    Task service: CapabilityStatement-task.html
    Terminology service: CapabilityStatement-terminology.html
  #Capability Statements: capability-statements.html
  Downloads: downloads.html
